name: deploy

on:
  release:
    types: [created, edited]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configura o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'
    - name: Instala os requisitos do módulo
      run: |
        pip install -r dev-requirements.txt
    - name: Executa os testes do pacote
      run: |
        pytest --cov=idecomp tests/
    - name: Veriricações de qualidade de código - tipagem estática
      run: |
        mypy ./idecomp
    - name: Verificações de qualidade de código - linter PEP8
      run: |
        pylama --ignore E203 ./idecomp
    - name: Instala dependências e constroi o pacote
      if: startsWith(github.ref, 'refs/tags')
      run: |
        pip install --upgrade pip setuptools wheel twine
        python setup.py sdist bdist_wheel
    - name: Publica o pacote no PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
